# Generated by Django 4.2.13 on 2025-11-17 15:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='年级名称')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, unique=True, verbose_name='学号')),
                ('total_hours', models.PositiveIntegerField(default=0, verbose_name='总服务时长')),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='总经验值')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=2, verbose_name='性别')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.grade', verbose_name='年级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '志愿者档案',
                'verbose_name_plural': '志愿者档案',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('description', ckeditor.fields.RichTextField(verbose_name='活动详情')),
                ('status', models.CharField(choices=[('报名中', '报名中'), ('进行中', '进行中'), ('已结束', '已结束')], default='报名中', max_length=10, verbose_name='活动状态')),
                ('hours_reward', models.PositiveIntegerField(default=0, verbose_name='可获时长')),
                ('min_xp', models.PositiveIntegerField(default=0, verbose_name='最低经验值要求')),
                ('max_xp', models.PositiveIntegerField(default=10000, verbose_name='最高经验值要求')),
                ('gender_restriction', models.CharField(choices=[('不限', '不限'), ('男', '男'), ('女', '女')], default='不限', max_length=2, verbose_name='性别限制')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='设置为0表示无人数限制', verbose_name='名额上限')),
                ('grade_restriction', models.ManyToManyField(blank=True, to='volunteer.grade', verbose_name='年级限制')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('phone_number', models.CharField(max_length=20, verbose_name='手机号')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('headteacher_name', models.CharField(max_length=50, verbose_name='班主任姓名')),
                ('status', models.CharField(choices=[('Pending', '待审核'), ('Approved', '已批准'), ('Rejected', '已拒绝')], default='Pending', max_length=10, verbose_name='审核状态')),
                ('hours_awarded', models.PositiveIntegerField(default=0, help_text='本次报名实际获得的时长', verbose_name='获得时长')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.activity', verbose_name='活动')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteerprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'unique_together': {('student', 'activity')},
            },
        ),
    ]
