# Generated by Django 4.2.13 on 2025-11-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('xp_bonus', models.PositiveIntegerField(default=0, verbose_name='额外经验加成')),
            ],
            options={
                'verbose_name': '学生标签/职务',
                'verbose_name_plural': '学生标签/职务',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='活动结束日期'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='活动开始日期'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='设置为0表示无人数限制', verbose_name='总名额上限'),
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='地点')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='本场次名额')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='volunteer.activity', verbose_name='所属活动')),
            ],
            options={
                'verbose_name': '活动场次',
                'verbose_name_plural': '活动场次',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registration',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='volunteer.activitysession', verbose_name='选择场次'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='volunteer.studenttag', verbose_name='职务/标签'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'activity', 'session')},
        ),
    ]
