# Generated by Django 4.2.13 on 2025-11-23 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0002_studenttag_activity_end_date_activity_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='留言内容')),
                ('color', models.CharField(choices=[('warning', '暖阳黄'), ('info', '天空蓝'), ('success', '草地绿'), ('danger', '樱花粉'), ('primary', '静谧紫')], default='warning', max_length=20, verbose_name='便利贴颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('is_public', models.BooleanField(default=True, help_text='如果不仅是给管理员看的建议，请勾选', verbose_name='是否公开')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言者')),
            ],
            options={
                'verbose_name': '心声/留言',
                'verbose_name_plural': '心声/留言',
                'ordering': ['-created_at'],
            },
        ),
    ]
