# Generated by Django 4.2.13 on 2025-11-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_messagewall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagewall',
            name='is_public',
            field=models.BooleanField(default=True, help_text='取消勾选则仅管理员可见', verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='messagewall',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='勾选后其他人看不到你的姓名', verbose_name='匿名发布'),
        ),
    ]
